### PR TITLE
feat: refresh function

### PR DESCRIPTION
**Pull request by strackfeldt**
extracted the refresh function of verify into a separate function, to enable storing access tokens in memory in a spa setup

### CODE REVIEW

**Comment by thdxr** [comment]
lol we were just talking about adding this today - need to tweak what you have a little but will do later today

**Comment by thdxr** [comment]
uh idk why this closed

**Comment by thdxr** [comment]
damn i messed something up that was dumb - can you force push what you have locally to your branch

**Comment by thdxr** [comment]
nvm we got it here #44

**Comment by strackfeldt** [comment]
haha nice thank you

what are your thoughts on having an option for the authorizer to set a http only cookie for the refresh token?

**Pull request closed without merging**
